In [85]:
import pandas as pd
import numpy as np
pd.set_option('future.no_silent_downcasting', True)

# Reading the Data

In [86]:
df = pd.read_json('Telco-Customer-Churn.json')
df.head()

customerID Churn                                           customer  \
0  0002-ORFBO    No  {'gender': 'Female', 'SeniorCitizen': 0, 'Part...   
1  0003-MKNFE    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...   
2  0004-TLHLJ   Yes  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...   
3  0011-IGKFF   Yes  {'gender': 'Male', 'SeniorCitizen': 1, 'Partne...   
4  0013-EXCHZ   Yes  {'gender': 'Female', 'SeniorCitizen': 1, 'Part...   

                                             phone  \
0   {'PhoneService': 'Yes', 'MultipleLines': 'No'}   
1  {'PhoneService': 'Yes', 'MultipleLines': 'Yes'}   
2   {'PhoneService': 'Yes', 'MultipleLines': 'No'}   
3   {'PhoneService': 'Yes', 'MultipleLines': 'No'}   
4   {'PhoneService': 'Yes', 'MultipleLines': 'No'}   

                                            internet  \
0  {'InternetService': 'DSL', 'OnlineSecurity': '...   
1  {'InternetService': 'DSL', 'OnlineSecurity': '...   
2  {'InternetService': 'Fiber optic', 'OnlineSecu...   
3  {'InternetService': 'Fiber optic', 'OnlineSecu...   
4  {'InternetService': 'Fiber optic', 'OnlineSecu...   

                                             account  
0  {'Contract': 'One year', 'PaperlessBilling': '...  
1  {'Contract': 'Month-to-month', 'PaperlessBilli...  
2  {'Contract': 'Month-to-month', 'PaperlessBilli...  
3  {'Contract': 'Month-to-month', 'PaperlessBilli...  
4  {'Contract': 'Month-to-month', 'PaperlessBilli...

In [87]:
aux = pd.json_normalize(df['customer'])
data = pd.concat([df, aux], axis = 1)
aux = pd.json_normalize(df['phone'])
data = pd.concat([data, aux], axis = 1)
aux = pd.json_normalize(df['internet'])
data = pd.concat([data, aux], axis = 1)
aux = pd.json_normalize(df['account'])
data = pd.concat([data, aux], axis = 1)
data.drop(['phone', 'internet', 'customer', 'account'], axis = 1, inplace = True)
data.head()

customerID Churn  gender  SeniorCitizen Partner Dependents  tenure  \
0  0002-ORFBO    No  Female              0     Yes        Yes       9   
1  0003-MKNFE    No    Male              0      No         No       9   
2  0004-TLHLJ   Yes    Male              0      No         No       4   
3  0011-IGKFF   Yes    Male              1     Yes         No      13   
4  0013-EXCHZ   Yes  Female              1     Yes         No       3   

  PhoneService MultipleLines InternetService  ... OnlineBackup  \
0          Yes            No             DSL  ...          Yes   
1          Yes           Yes             DSL  ...           No   
2          Yes            No     Fiber optic  ...           No   
3          Yes            No     Fiber optic  ...          Yes   
4          Yes            No     Fiber optic  ...           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No         Yes         Yes              No        One year   
1               No          No          No             Yes  Month-to-month   
2              Yes          No          No              No  Month-to-month   
3              Yes          No         Yes             Yes  Month-to-month   
4               No         Yes         Yes              No  Month-to-month   

  PaperlessBilling     PaymentMethod Charges.Monthly  Charges.Total  
0              Yes      Mailed check            65.6          593.3  
1               No      Mailed check            59.9          542.4  
2              Yes  Electronic check            73.9         280.85  
3              Yes  Electronic check            98.0        1237.85  
4              Yes      Mailed check            83.9          267.4  

[5 rows x 21 columns]

# Data Dictionary

## Df coulumns

In [88]:
data.columns

Index(['customerID', 'Churn', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly',
       'Charges.Total'],
      dtype='object')

## Understanding the columns values

In [89]:
data.customerID.head()

0    0002-ORFBO
1    0003-MKNFE
2    0004-TLHLJ
3    0011-IGKFF
4    0013-EXCHZ
Name: customerID, dtype: object

In [90]:
data['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

In [91]:
data['Churn'][data['Churn'] == 'No'].count()

np.int64(5174)

In [92]:
data['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [93]:
data['SeniorCitizen'].unique()

array([0, 1])

In [94]:
data['Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [95]:
data['Dependents'].unique()

array(['Yes', 'No'], dtype=object)

In [96]:
data['tenure'].unique()

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72,  5, 56, 34,  1, 45, 50, 23,
       55, 26, 69, 11, 37, 49, 66, 67, 20, 43, 59, 12, 27,  2, 25, 29, 14,
       35, 64, 39, 40,  6, 30, 70, 57, 58, 16, 32, 33, 10, 21, 61, 15, 44,
       22, 24, 19, 47, 62, 46, 52,  8, 60, 48, 28, 41, 53, 68, 51, 31, 36,
       17, 18, 38, 42,  0])

In [97]:
data['PhoneService'].unique()

array(['Yes', 'No'], dtype=object)

In [98]:
data['MultipleLines'].unique()

array(['No', 'Yes', 'No phone service'], dtype=object)

In [99]:
data['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [100]:
data['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [101]:
data['OnlineBackup'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [102]:
data['DeviceProtection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [103]:
data['TechSupport'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [104]:
data['StreamingTV'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [105]:
data['Contract'].unique()

array(['One year', 'Month-to-month', 'Two year'], dtype=object)

In [106]:
data['PaperlessBilling'].unique()

array(['Yes', 'No'], dtype=object)

In [107]:
data['Charges.Total'].unique()

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

## Data dictionary
customerID - String containing an Id for each customer - <b> String </b></br>
Churn - Column filled with Ýes'or 'No', indicating if a customer left our services - <b> String </b></br>
gender - String with customer gender - <b> String </b> </br>
SeniorCitizen - 0 or 1 indicating if a customer is a Senior - <b> Integer </b></br>
Partner - Column of 'Yes' and 'No' that tells if a customer has a partner - <b> String </b></br>
Dependents - Column of 'Yes' and 'No' that tells if a customer has a dependents - <b> String </b></br>
tenure - Time that a client is with the company - <b> Integer </b></br>
PhoneService - If the client has Phone Service with the company - <b> String </b></br>
MultipleLines - If the client has more than one phone line - <b> String </b></br>
InternetService - If the client has internet service, it's filled with de kind of service (DSL or Fiber optic), else it has 'No' as a value - <b> String </b></br>
OnlineSecurity - If the customer hired an Online Security Service - <b> String </b> </br>
OnlineBackup - If the customer hired an Online Backup Service - <b> String </b></br>
DeviceProtection - If the customer hired a Device Protection Services - <b> String </b></br>
TechSupport - If the customer hired a Tech Support Services - <b> String </b></br>
StreamingTV - If the customer hired a TV Streaming Service - <b> String </b></br>
StreamingMovies - If the customer hired a Movie Streaming Service - <b> String </b></br>
Contract - Customer contract category - <b> String </b></br>
PaperlessBilling - If the customer uses paperless billing - <b> String </b></br>
PaymentMethod - Customer payment method - <b> String </b></br>
Charges.Monthly - Value of the charge per month - <b> Float </b></br>
Charges.Total - Value payed by the customer for the time it hired the company - <b> Float </b>

### Data Types on the DataFrame

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7267 non-null   object 
 1   Churn             7267 non-null   object 
 2   gender            7267 non-null   object 
 3   SeniorCitizen     7267 non-null   int64  
 4   Partner           7267 non-null   object 
 5   Dependents        7267 non-null   object 
 6   tenure            7267 non-null   int64  
 7   PhoneService      7267 non-null   object 
 8   MultipleLines     7267 non-null   object 
 9   InternetService   7267 non-null   object 
 10  OnlineSecurity    7267 non-null   object 
 11  OnlineBackup      7267 non-null   object 
 12  DeviceProtection  7267 non-null   object 
 13  TechSupport       7267 non-null   object 
 14  StreamingTV       7267 non-null   object 
 15  StreamingMovies   7267 non-null   object 
 16  Contract          7267 non-null   object 


# Correcting the inconsistencies

As we can see from the cell above, some columns are stored with the wrong data type, to fix this, we'll make some trasnformations on the dataset. We'll also change the string columns that have "Yes" and "No" to boolean True or False. The empty lines on that columns will be filled with False.

## CustomerID
Nothing to do in this column.
## Churn
Drop '', replace 'Yes' for 1 and 'No' for 0

In [109]:
data = data[data['Churn'] != '']
data['Churn']= data['Churn'].replace({'Yes' : 1, 'No': 0}).astype('int64')

data.Churn.unique()

array([0, 1])

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   Churn             7043 non-null   int64  
 2   gender            7043 non-null   object 
 3   SeniorCitizen     7043 non-null   int64  
 4   Partner           7043 non-null   object 
 5   Dependents        7043 non-null   object 
 6   tenure            7043 non-null   int64  
 7   PhoneService      7043 non-null   object 
 8   MultipleLines     7043 non-null   object 
 9   InternetService   7043 non-null   object 
 10  OnlineSecurity    7043 non-null   object 
 11  OnlineBackup      7043 non-null   object 
 12  DeviceProtection  7043 non-null   object 
 13  TechSupport       7043 non-null   object 
 14  StreamingTV       7043 non-null   object 
 15  StreamingMovies   7043 non-null   object 
 16  Contract          7043 non-null   object 
 17  

## Gender
Nothing needed to be done.
## SeniorCitizen
Nothing needed to be done

## Partner
Replace Yes and No's for 1's and 0's
## Dependents
Same as above

In [111]:
data['Partner']= data['Partner'].replace({'Yes' : 1, 'No' : 0})
data['Partner'] = data['Partner'].infer_objects(copy=False)

data.Partner.unique()

array([1, 0])

In [112]:
data['Dependents']= data['Dependents'].replace({'Yes' : 1, 'No' : 0})
data['Dependents'] = data['Dependents'].infer_objects(copy=False)

data.Dependents.unique()

array([1, 0])

## Tenure
Nothing to be done
## PhoneService
Replace Yes and No for 1's and 0's
## MultipleLines
Same as above, but also replace 'No Phone Service' for 0

In [113]:
data['PhoneService']= data['PhoneService'].replace({'Yes' : 1, 'No' : 0})
data['PhoneService'] = data['PhoneService'].infer_objects(copy=False)

data['MultipleLines']= data['MultipleLines'].replace({'Yes' : 1, 'No' : 0, 'No phone service' : 0})
data['MultipleLines'] = data['MultipleLines'].infer_objects(copy=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   Churn             7043 non-null   int64  
 2   gender            7043 non-null   object 
 3   SeniorCitizen     7043 non-null   int64  
 4   Partner           7043 non-null   int64  
 5   Dependents        7043 non-null   int64  
 6   tenure            7043 non-null   int64  
 7   PhoneService      7043 non-null   int64  
 8   MultipleLines     7043 non-null   int64  
 9   InternetService   7043 non-null   object 
 10  OnlineSecurity    7043 non-null   object 
 11  OnlineBackup      7043 non-null   object 
 12  DeviceProtection  7043 non-null   object 
 13  TechSupport       7043 non-null   object 
 14  StreamingTV       7043 non-null   object 
 15  StreamingMovies   7043 non-null   object 
 16  Contract          7043 non-null   object 
 17  

In [114]:
data.MultipleLines.unique()

array([0, 1])

## InternetService
Nothing to be done
## OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV and StreamingMovies
Replace Yes for 1, No and No internet service for 0

In [115]:
data['OnlineSecurity']= data['OnlineSecurity'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['OnlineSecurity'] = data['OnlineSecurity'].infer_objects(copy=False)

data['OnlineBackup']= data['OnlineBackup'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['OnlineBackup'] = data['OnlineBackup'].infer_objects(copy=False)

data['DeviceProtection']= data['DeviceProtection'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['DeviceProtection'] = data['DeviceProtection'].infer_objects(copy=False)

data['TechSupport']= data['TechSupport'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['TechSupport'] = data['TechSupport'].infer_objects(copy=False)

data['StreamingTV']= data['StreamingTV'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['StreamingTV'] = data['StreamingTV'].infer_objects(copy=False)

data['StreamingMovies']= data['StreamingMovies'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['StreamingMovies'] = data['StreamingMovies'].infer_objects(copy=False)

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   Churn             7043 non-null   int64  
 2   gender            7043 non-null   object 
 3   SeniorCitizen     7043 non-null   int64  
 4   Partner           7043 non-null   int64  
 5   Dependents        7043 non-null   int64  
 6   tenure            7043 non-null   int64  
 7   PhoneService      7043 non-null   int64  
 8   MultipleLines     7043 non-null   int64  
 9   InternetService   7043 non-null   object 
 10  OnlineSecurity    7043 non-null   int64  
 11  OnlineBackup      7043 non-null   int64  
 12  DeviceProtection  7043 non-null   int64  
 13  TechSupport       7043 non-null   int64  
 14  StreamingTV       7043 non-null   int64  
 15  StreamingMovies   7043 non-null   int64  
 16  Contract          7043 non-null   object 
 17  

## Contract
Nothing to be done
## PaperlessBilling
Replace Yes for 1 No for 0
## PaymentMethod and Charges.Monthly
Nothing to be done
## Charges.Total
Change type to float64

In [116]:
data['PaperlessBilling']= data['PaperlessBilling'].replace({'Yes' : 1, 'No' : 0, 'No internet service' : 0})
data['PaperlessBilling'] = data['PaperlessBilling'].infer_objects(copy=False)

data['Charges.Total'] = data['Charges.Total'].replace(' ', np.nan)
data['Charges.Total'] = data['Charges.Total'].astype('float64')

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   Churn             7043 non-null   int64  
 2   gender            7043 non-null   object 
 3   SeniorCitizen     7043 non-null   int64  
 4   Partner           7043 non-null   int64  
 5   Dependents        7043 non-null   int64  
 6   tenure            7043 non-null   int64  
 7   PhoneService      7043 non-null   int64  
 8   MultipleLines     7043 non-null   int64  
 9   InternetService   7043 non-null   object 
 10  OnlineSecurity    7043 non-null   int64  
 11  OnlineBackup      7043 non-null   int64  
 12  DeviceProtection  7043 non-null   int64  
 13  TechSupport       7043 non-null   int64  
 14  StreamingTV       7043 non-null   int64  
 15  StreamingMovies   7043 non-null   int64  
 16  Contract          7043 non-null   object 
 17  

# Checking for inconsistencies on charges total

In [117]:
aux = data[data['Charges.Total'] != (data['tenure'] * data['Charges.Monthly'])]
aux

customerID  Churn  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     0002-ORFBO      0  Female              0        1           1       9   
1     0003-MKNFE      0    Male              0        0           0       9   
2     0004-TLHLJ      1    Male              0        0           0       4   
3     0011-IGKFF      1    Male              1        1           0      13   
4     0013-EXCHZ      1  Female              1        1           0       3   
...          ...    ...     ...            ...      ...         ...     ...   
7262  9987-LUTYD      0  Female              0        0           0      13   
7263  9992-RRAMN      1    Male              0        1           0      22   
7264  9992-UJOEL      0    Male              0        0           0       2   
7265  9993-LHIEB      0    Male              0        1           1      67   
7266  9995-HOTOH      0    Male              0        1           1      63   

      PhoneService  MultipleLines InternetService  ...  OnlineBackup  \
0                1              0             DSL  ...             1   
1                1              1             DSL  ...             0   
2                1              0     Fiber optic  ...             0   
3                1              0     Fiber optic  ...             1   
4                1              0     Fiber optic  ...             0   
...            ...            ...             ...  ...           ...   
7262             1              0             DSL  ...             0   
7263             1              1     Fiber optic  ...             0   
7264             1              0             DSL  ...             1   
7265             1              0             DSL  ...             0   
7266             0              0             DSL  ...             1   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                    0            1            1                0   
1                    0            0            0                1   
2                    1            0            0                0   
3                    1            0            1                1   
4                    0            1            1                0   
...                ...          ...          ...              ...   
7262                 0            1            0                0   
7263                 0            0            0                1   
7264                 0            0            0                0   
7265                 1            1            0                1   
7266                 1            0            1                1   

            Contract PaperlessBilling     PaymentMethod Charges.Monthly  \
0           One year                1      Mailed check           65.60   
1     Month-to-month                0      Mailed check           59.90   
2     Month-to-month                1  Electronic check           73.90   
3     Month-to-month                1  Electronic check           98.00   
4     Month-to-month                1      Mailed check           83.90   
...              ...              ...               ...             ...   
7262        One year                0      Mailed check           55.15   
7263  Month-to-month                1  Electronic check           85.10   
7264  Month-to-month                1      Mailed check           50.30   
7265        Two year                0      Mailed check           67.85   
7266        Two year                0  Electronic check           59.00   

      Charges.Total  
0            593.30  
1            542.40  
2            280.85  
3           1237.85  
4            267.40  
...             ...  
7262         742.90  
7263        1873.70  
7264          92.75  
7265        4627.65  
7266        3707.60  

[6429 rows x 21 columns]

We can see that we have a lot of cases that the charges total don't match the tenure time * charges.monthly. To fix that we'll create a new column named Charges.Calculated

In [118]:
data['Charges.Calculated'] = data['tenure'] * data['Charges.Monthly']
data.head()

customerID  Churn  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  0002-ORFBO      0  Female              0        1           1       9   
1  0003-MKNFE      0    Male              0        0           0       9   
2  0004-TLHLJ      1    Male              0        0           0       4   
3  0011-IGKFF      1    Male              1        1           0      13   
4  0013-EXCHZ      1  Female              1        1           0       3   

   PhoneService  MultipleLines InternetService  ...  DeviceProtection  \
0             1              0             DSL  ...                 0   
1             1              1             DSL  ...                 0   
2             1              0     Fiber optic  ...                 1   
3             1              0     Fiber optic  ...                 1   
4             1              0     Fiber optic  ...                 0   

   TechSupport  StreamingTV  StreamingMovies        Contract  \
0            1            1                0        One year   
1            0            0                1  Month-to-month   
2            0            0                0  Month-to-month   
3            0            1                1  Month-to-month   
4            1            1                0  Month-to-month   

   PaperlessBilling     PaymentMethod  Charges.Monthly Charges.Total  \
0                 1      Mailed check             65.6        593.30   
1                 0      Mailed check             59.9        542.40   
2                 1  Electronic check             73.9        280.85   
3                 1  Electronic check             98.0       1237.85   
4                 1      Mailed check             83.9        267.40   

   Charges.Calculated  
0               590.4  
1               539.1  
2               295.6  
3              1274.0  
4               251.7  

[5 rows x 22 columns]

In [119]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   customerID          7043 non-null   object 
 1   Churn               7043 non-null   int64  
 2   gender              7043 non-null   object 
 3   SeniorCitizen       7043 non-null   int64  
 4   Partner             7043 non-null   int64  
 5   Dependents          7043 non-null   int64  
 6   tenure              7043 non-null   int64  
 7   PhoneService        7043 non-null   int64  
 8   MultipleLines       7043 non-null   int64  
 9   InternetService     7043 non-null   object 
 10  OnlineSecurity      7043 non-null   int64  
 11  OnlineBackup        7043 non-null   int64  
 12  DeviceProtection    7043 non-null   int64  
 13  TechSupport         7043 non-null   int64  
 14  StreamingTV         7043 non-null   int64  
 15  StreamingMovies     7043 non-null   int64  
 16  Contract   

# Checking for inconsistencies on Phone Service

In [120]:
aux = data[['PhoneService', 'MultipleLines']][(data['PhoneService'] == False) & (data['MultipleLines'])]
aux

Empty DataFrame
Columns: [PhoneService, MultipleLines]
Index: []

In [121]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   customerID          7043 non-null   object 
 1   Churn               7043 non-null   int64  
 2   gender              7043 non-null   object 
 3   SeniorCitizen       7043 non-null   int64  
 4   Partner             7043 non-null   int64  
 5   Dependents          7043 non-null   int64  
 6   tenure              7043 non-null   int64  
 7   PhoneService        7043 non-null   int64  
 8   MultipleLines       7043 non-null   int64  
 9   InternetService     7043 non-null   object 
 10  OnlineSecurity      7043 non-null   int64  
 11  OnlineBackup        7043 non-null   int64  
 12  DeviceProtection    7043 non-null   int64  
 13  TechSupport         7043 non-null   int64  
 14  StreamingTV         7043 non-null   int64  
 15  StreamingMovies     7043 non-null   int64  
 16  Contract   

# Checking for inconsistencies on Internet Service

In [122]:
aux = data[['InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']][(data['InternetService'] == False) & ((data['OnlineSecurity']) | (data['OnlineBackup']) | (data['DeviceProtection']) | (data['TechSupport']) | (data['StreamingTV']) | (data['StreamingMovies']))]
aux

Empty DataFrame
Columns: [InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies]
Index: []

# Creating Daily expenses column

In [123]:
data['DailyExpense'] = data['Charges.Calculated'] / (data['tenure'] * 30)

In [124]:
data.to_csv('cleaned_churn_data.csv', index = False)

In [125]:
data

customerID  Churn  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     0002-ORFBO      0  Female              0        1           1       9   
1     0003-MKNFE      0    Male              0        0           0       9   
2     0004-TLHLJ      1    Male              0        0           0       4   
3     0011-IGKFF      1    Male              1        1           0      13   
4     0013-EXCHZ      1  Female              1        1           0       3   
...          ...    ...     ...            ...      ...         ...     ...   
7262  9987-LUTYD      0  Female              0        0           0      13   
7263  9992-RRAMN      1    Male              0        1           0      22   
7264  9992-UJOEL      0    Male              0        0           0       2   
7265  9993-LHIEB      0    Male              0        1           1      67   
7266  9995-HOTOH      0    Male              0        1           1      63   

      PhoneService  MultipleLines InternetService  ...  TechSupport  \
0                1              0             DSL  ...            1   
1                1              1             DSL  ...            0   
2                1              0     Fiber optic  ...            0   
3                1              0     Fiber optic  ...            0   
4                1              0     Fiber optic  ...            1   
...            ...            ...             ...  ...          ...   
7262             1              0             DSL  ...            1   
7263             1              1     Fiber optic  ...            0   
7264             1              0             DSL  ...            0   
7265             1              0             DSL  ...            1   
7266             0              0             DSL  ...            0   

      StreamingTV  StreamingMovies        Contract  PaperlessBilling  \
0               1                0        One year                 1   
1               0                1  Month-to-month                 0   
2               0                0  Month-to-month                 1   
3               1                1  Month-to-month                 1   
4               1                0  Month-to-month                 1   
...           ...              ...             ...               ...   
7262            0                0        One year                 0   
7263            0                1  Month-to-month                 1   
7264            0                0  Month-to-month                 1   
7265            0                1        Two year                 0   
7266            1                1        Two year                 0   

         PaymentMethod Charges.Monthly  Charges.Total Charges.Calculated  \
0         Mailed check           65.60         593.30             590.40   
1         Mailed check           59.90         542.40             539.10   
2     Electronic check           73.90         280.85             295.60   
3     Electronic check           98.00        1237.85            1274.00   
4         Mailed check           83.90         267.40             251.70   
...                ...             ...            ...                ...   
7262      Mailed check           55.15         742.90             716.95   
7263  Electronic check           85.10        1873.70            1872.20   
7264      Mailed check           50.30          92.75             100.60   
7265      Mailed check           67.85        4627.65            4545.95   
7266  Electronic check           59.00        3707.60            3717.00   

      DailyExpense  
0         2.186667  
1         1.996667  
2         2.463333  
3         3.266667  
4         2.796667  
...            ...  
7262      1.838333  
7263      2.836667  
7264      1.676667  
7265      2.261667  
7266      1.966667  

[7043 rows x 23 columns]